--DEMONSTRAÇÃO DOS CLIENTES FRAUDADOS NA SAIDA, INFORMANDO O TOTAL DO VALOR FRAUDADO E A QUANTIDADE DE FRAUDES POR CLIENTES_ID.

SELECT T.cliente_id, C.NOME, C.EMAIL, CONCAT('R$', ROUND(SUM(T.valor), 2)) AS total, count(T.id) as TRANSACOES_POR_CLIENTE
FROM transacoes T
LEFT JOIN clientes C ON C.ID =  T.cliente_id
WHERE T.tipo = 'saida'
AND T.fraude = '1'
GROUP BY T.cliente_id, C.NOME, C.EMAIL
