--CRIAÇÃO DE VIEW PARA PORCENTAGEM DE FRAUDES

CREATE VIEW view_porc_fraudes AS
    SELECT 
        COUNT(ID) AS QUANTIDADES_FRAUDES, 
        TIPO,
        CONCAT(CAST(COUNT(ID) * 100.0 / SUM(COUNT(ID)) OVER () AS DECIMAL(5, 2)),'%') AS PORCENTAGEM
    FROM TRANSACOES
    WHERE FRAUDE = '1'
    GROUP BY TIPO;
	
	